name: CI/CD Pipeline for Rating App
on:
  push:
    branches:
      - main

env: 
  APP_NAME: rating-app
  NAMESPACE: project4

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.NEW_TAG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Generate New Tag
        id: tag
        run: |
          TAG=$(curl -s https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/k8s-rating-frontend/tags/?page_size=1 | jq -r '.results[0].name' || echo "cicdV0")
          NUM=$(echo $TAG | sed 's/[^0-9]*//g')
          NEXT=$((NUM + 1))
          NEW_TAG="cicdV$NEXT"
          echo "NEW_TAG=$NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/k8s-rating-frontend:${{ steps.tag.outputs.NEW_TAG }} --build-arg VITE_API_URL=http://myapp.local/api ./frontend
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend-rating-app:${{ steps.tag.outputs.NEW_TAG }} ./backend

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/k8s-rating-frontend:${{ steps.tag.outputs.NEW_TAG }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend-rating-app:${{ steps.tag.outputs.NEW_TAG }}

  deploy:
    name: Deploy to EKS using Helm
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Configure kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ap-south-1 --name my-cluster
          kubectl get nodes

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Helm Deploy
        run: |
          helm upgrade --install rating-app ./rating-app \
            --namespace project4 \
            --create-namespace \
            --set frontend.image=${{ secrets.DOCKERHUB_USERNAME }}/k8s-rating-frontend:${{ needs.build-and-push.outputs.tag }} \
            --set backend.image=${{ secrets.DOCKERHUB_USERNAME }}/backend-rating-app:${{ needs.build-and-push.outputs.tag }}

      # - name: Verify rollout
      #   run: |
      #     kubectl rollout status deployment/frontend-deployment -n project4
      #     kubectl rollout status deployment/backend-deployment -n project4

